# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://gambera.github.io/projetos/" # the subpath of your site, e.g. /blog/
url: "https://gambera.github.io/projetos/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
